import { renderSnapshot, getMeta } from '../../lib/snapshot.js'

// Generated by capture/report.mjs — edit capture/targets.json and re-run `pnpm report`.

export default {
  title: 'Journeys/Browse & Search/Search Results - Map View',
  parameters: {
    docs: {
      description: {
        component: `Full map view with clustered hotel markers and info windows.

**Source:** production capture of \`presto.eventpipe.com/event/9f16e139-935b-48f6-80cf-da2628b33b9c/shopKey/6a6b786d5171a074d8784f55/search\`
Rendered from the exact DOM the browser built, with production CSS, inside a shadow root.
Open the **Accessibility** panel to run axe against the real markup.`,
      },
    },
  },
}

export const Desktop = {
  name: 'Desktop 1440px',
  render: () => renderSnapshot({ journey: 'browse', id: 'search-map', viewport: 'desktop' }),
}

export const Mobile = {
  name: 'Mobile 390px',
  render: () => renderSnapshot({ journey: 'browse', id: 'search-map', viewport: 'mobile' }),
}
