// Generate the Storybook surface from captured evidence.
//
//   pnpm report
//
// Emits, per target:
//   src/stories/<journey>/<Name>.stories.js   the snapshot stories
//   src/stories/<journey>/<Name>.mdx          the findings page
// plus src/stories/Scorecard.mdx and docs/FINDINGS.md.
//
// Everything here is generated. Prose that needs a human — the remediation
// code — lives in capture/fixes.js and is imported, never invented at build time.

import { readFile, writeFile, mkdir, access } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, resolve, join } from 'node:path'
import { FIXES } from './fixes.js'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SNAP = join(ROOT, 'snapshots')
const STORIES = join(ROOT, 'src/stories')
const exists = (p) => access(p).then(() => true, () => false)

const cfg = JSON.parse(await readFile(join(ROOT, 'capture/targets.json'), 'utf8'))
const axe = (await exists(join(SNAP, 'findings.json')))
  ? JSON.parse(await readFile(join(SNAP, 'findings.json'), 'utf8'))
  : { findings: [], summary: [] }
const structural = (await exists(join(SNAP, 'structural.json')))
  ? JSON.parse(await readFile(join(SNAP, 'structural.json'), 'utf8'))
  : { findings: [] }

const JOURNEY_TITLES = {
  browse: 'Browse & Search',
  details: 'Hotel Details',
  checkout: 'Checkout',
  confirmation: 'Confirmation',
  managebooking: 'Manage Booking',
  appshell: 'App Shell',
}

const IMPACT_RANK = { critical: 0, serious: 1, moderate: 2, minor: 3 }
const esc = (s = '') => String(s).replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
/**
 * Escape prose for MDX, leaving inline code spans alone.
 *
 * MDX reads `<` as a JSX tag and `{` as an expression, so prose must escape
 * both. Inside a backtick span the content is already literal, and escaping it
 * there renders the entity itself — a note reading `<span lang="fr">` comes out
 * as `&lt;span lang="fr"&gt;`. So split on code spans and escape only around them.
 */
const mdxSafe = (s = '') =>
  String(s)
    .split(/(`[^`]*`)/g)
    .map((part) =>
      part.startsWith('`') && part.endsWith('`') && part.length > 1
        ? part
        : part.replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\{/g, '&#123;').replace(/\}/g, '&#125;')
    )
    .join('')

// Code spans and fences are already literal in MDX — running prose escaping over
// them renders the entities themselves (`&lt;input&gt;` instead of `<input>`).
// These only neutralise the delimiter that would break out of the code context.
const codeInline = (s = '') => String(s).replace(/`/g, "'").replace(/\r?\n/g, ' ')
const codeBlock = (s = '') => String(s).replace(/```/g, "'''")
const pascal = (s) => s.replace(/(^|[-_])(\w)/g, (_, __, c) => c.toUpperCase())

/** All findings for one page, axe + structural, normalised and ranked. */
function findingsFor(pageId) {
  const fromAxe = axe.findings
    .filter((f) => f.page === pageId)
    .map((f) => ({
      source: 'axe-core',
      id: f.rule,
      impact: f.impact,
      level: f.level,
      sc: f.sc,
      title: f.help,
      detail: '',
      viewport: f.viewport,
      count: f.nodeCount,
      helpUrl: f.helpUrl,
      nodes: f.nodes,
      evidence: [],
    }))
  const fromStruct = structural.findings
    .filter((f) => f.page === pageId)
    .map((f) => ({
      source: 'manual',
      id: f.id,
      impact: f.impact,
      level: f.level,
      sc: f.sc,
      title: f.title,
      detail: f.detail,
      viewport: f.viewport,
      count: f.nodes?.length ?? 1,
      helpUrl: null,
      nodes: f.nodes ?? [],
      evidence: f.evidence ?? [],
    }))

  // Collapse the same rule reported on both viewports into one row.
  const merged = new Map()
  for (const f of [...fromStruct, ...fromAxe]) {
    const k = f.id
    if (!merged.has(k)) {
      merged.set(k, { ...f, viewports: new Set([f.viewport]) })
    } else {
      const m = merged.get(k)
      m.viewports.add(f.viewport)
      m.count = Math.max(m.count, f.count)
      if (!m.detail && f.detail) m.detail = f.detail
      if (!m.evidence.length && f.evidence.length) m.evidence = f.evidence
      if (!m.nodes.length && f.nodes.length) m.nodes = f.nodes
    }
  }
  return [...merged.values()]
    .map((f) => ({ ...f, viewports: [...f.viewports] }))
    .sort((a, b) => (IMPACT_RANK[a.impact] ?? 9) - (IMPACT_RANK[b.impact] ?? 9) || b.count - a.count)
}

function storyFile(target) {
  const journeyTitle = JOURNEY_TITLES[target.journey] ?? target.journey
  return `import { renderSnapshot, getMeta } from '../../lib/snapshot.js'

// Generated by capture/report.mjs — edit capture/targets.json and re-run \`pnpm report\`.

export default {
  title: 'Journeys/${journeyTitle}/${esc(target.title)}',
  parameters: {
    docs: {
      description: {
        component: \`${esc(target.description || '')}

**Source:** production capture of \\\`${esc((target.url || target.flow?.start || 'pending').replace(/^https?:\/\//, ''))}\\\`
Rendered from the exact DOM the browser built, with production CSS, inside a shadow root.
Open the **Accessibility** panel to run axe against the real markup.\`,
      },
    },
  },
}

export const Desktop = {
  name: 'Desktop 1440px',
  render: () => renderSnapshot({ journey: '${target.journey}', id: '${target.id}', viewport: 'desktop' }),
}

export const Mobile = {
  name: 'Mobile 390px',
  render: () => renderSnapshot({ journey: '${target.journey}', id: '${target.id}', viewport: 'mobile' }),
}
`
}

function findingsDoc(target, findings) {
  const journeyTitle = JOURNEY_TITLES[target.journey] ?? target.journey
  const captured = findings.length > 0
  const counts = { critical: 0, serious: 0, moderate: 0, minor: 0 }
  for (const f of findings) counts[f.impact] = (counts[f.impact] || 0) + 1

  const head = `import { Meta } from '@storybook/addon-docs/blocks'

<Meta title="Journeys/${journeyTitle}/${esc(target.title)} — Findings" />

# ${mdxSafe(target.title)} — Findings

${mdxSafe(target.description || '')}

${
  target.url || target.flow?.start
    ? `**Captured from:** \`${codeInline(target.url || target.flow?.start)}\``
    : `> **Not yet captured.** ${mdxSafe(target.note || 'This page is gated behind a completed booking or an authenticated session.')}
>
> Add its URL to \`capture/targets.json\` and run \`pnpm capture && pnpm audit && pnpm report\`.`
}
`

  if (!captured) {
    return `${head}
---

No findings yet — this page has not been captured.
`
  }

  const summary = `
---

## Summary

| Impact | Count |
| --- | --- |
| Critical | ${counts.critical} |
| Serious | ${counts.serious} |
| Moderate | ${counts.moderate} |
| Minor | ${counts.minor} |

${findings.length} distinct issue${findings.length === 1 ? '' : 's'} on this page.

---
`

  const body = findings
    .map((f, i) => {
      const fix = FIXES[f.id]
      const scList = f.sc.length ? f.sc.map((s) => `${s}`).join(', ') : '—'

      const evidence = f.evidence.length
        ? `**Evidence**

${f.evidence.map((e) => `- \`${codeInline(e)}\``).join('\n')}
`
        : ''

      const nodes = f.nodes.length
        ? `<details>
<summary>Affected elements (${f.nodes.length}${f.count > f.nodes.length ? ` of ${f.count}` : ''})</summary>

${f.nodes
  .slice(0, 12)
  .map(
    (n) => `\`\`\`html
<!-- ${codeBlock((Array.isArray(n.target) ? n.target[0] : n.target) || '')} -->
${codeBlock((n.html || '').trim())}
\`\`\``
  )
  .join('\n\n')}

</details>
`
        : ''

      const remediation = fix
        ? `#### Fix — ${mdxSafe(fix.title)}

${mdxSafe(fix.why)}

${fix.before ? `**Before** (production)\n\n\`\`\`html\n${fix.before}\n\`\`\`\n` : ''}
${fix.after ? `**After**\n\n\`\`\`html\n${fix.after}\n\`\`\`\n` : ''}
${fix.quasar ? `**Vue / Quasar form**\n\n\`\`\`html\n${fix.quasar}\n\`\`\`\n` : ''}
${fix.notes?.length ? `**Notes**\n\n${fix.notes.map((n) => `- ${mdxSafe(n)}`).join('\n')}\n` : ''}
**Effort:** ${fix.effort} &nbsp;•&nbsp; **Owner:** ${mdxSafe(fix.owner)}
`
        : `#### Fix

_No bespoke remediation authored for \`${codeInline(f.id)}\` yet._${f.helpUrl ? ` See the [axe rule reference](${f.helpUrl}).` : ''}
`

      return `### ${i + 1}. ${mdxSafe(f.title)}

<span class="f-badge ${f.impact}">${f.impact}</span> <span class="f-badge sc">WCAG ${scList} (Level ${f.level})</span>

| | |
| --- | --- |
| **Rule** | \`${codeInline(f.id)}\` |
| **Detected by** | ${f.source} |
| **Occurrences** | ${f.count} |
| **Viewports** | ${f.viewports.join(', ')} |
${f.helpUrl ? `| **Reference** | [${mdxSafe(f.id)}](${f.helpUrl}) |` : ''}

${f.detail ? `${mdxSafe(f.detail)}\n` : ''}
${evidence}
${nodes}
${remediation}
---
`
    })
    .join('\n')

  return head + summary + body
}

// --- write per-target files --------------------------------------------------
let storyCount = 0
const scorecard = []

for (const target of cfg.targets) {
  const dir = join(STORIES, target.journey)
  await mkdir(dir, { recursive: true })
  const name = pascal(target.id)

  await writeFile(join(dir, `${name}.stories.js`), storyFile(target))
  const findings = findingsFor(target.id)
  await writeFile(join(dir, `${name}.mdx`), findingsDoc(target, findings))
  storyCount++

  const counts = { critical: 0, serious: 0, moderate: 0, minor: 0 }
  for (const f of findings) counts[f.impact] = (counts[f.impact] || 0) + 1
  const hasSnapshot = await exists(join(SNAP, target.journey, target.id, 'desktop.html'))
  scorecard.push({
    journey: target.journey,
    journeyTitle: JOURNEY_TITLES[target.journey] ?? target.journey,
    id: target.id,
    title: target.title,
    captured: hasSnapshot,
    findings: findings.length,
    ...counts,
    elements: findings.reduce((a, f) => a + f.count, 0),
  })
}

// --- scorecard ---------------------------------------------------------------
const tot = scorecard.reduce(
  (a, r) => ({
    critical: a.critical + r.critical,
    serious: a.serious + r.serious,
    moderate: a.moderate + r.moderate,
    minor: a.minor + r.minor,
    elements: a.elements + r.elements,
  }),
  { critical: 0, serious: 0, moderate: 0, minor: 0, elements: 0 }
)

const ruleRows = [...axe.summary]
  .sort((a, b) => (IMPACT_RANK[a.impact] ?? 9) - (IMPACT_RANK[b.impact] ?? 9) || b.nodes - a.nodes)
  .map((r) => `| \`${r.rule}\` | ${r.impact} | ${r.sc.join(', ') || '—'} | ${r.nodes} | ${r.pages.length} |`)
  .join('\n')

const structRules = new Map()
for (const f of structural.findings) {
  const k = f.id
  structRules.set(k, {
    id: k,
    impact: f.impact,
    sc: f.sc.join(', '),
    pages: (structRules.get(k)?.pages ?? 0) + 1,
    title: f.title,
  })
}
const structRows = [...structRules.values()]
  .sort((a, b) => (IMPACT_RANK[a.impact] ?? 9) - (IMPACT_RANK[b.impact] ?? 9))
  .map((r) => `| \`${r.id}\` | ${r.impact} | ${r.sc} | ${r.pages} |`)
  .join('\n')

const scorecardMdx = `import { Meta } from '@storybook/addon-docs/blocks'

<Meta title="Getting Started/Scorecard" />

# Scorecard

Production accessibility audit of the EventPipe / Presto booking journey, against
**WCAG 2.2 Level AA**, at **1440px desktop** and **390px mobile**.

## Totals

| Impact | Distinct issues |
| --- | --- |
| Critical | ${tot.critical} |
| Serious | ${tot.serious} |
| Moderate | ${tot.moderate} |
| Minor | ${tot.minor} |

**${tot.elements}** individual element occurrences across all captured pages.

## By page

| Journey | Page | Captured | Critical | Serious | Moderate | Elements |
| --- | --- | --- | --- | --- | --- | --- |
${scorecard
  .map(
    (r) =>
      `| ${r.journeyTitle} | ${mdxSafe(r.title)} | ${r.captured ? 'yes' : 'pending'} | ${r.critical} | ${r.serious} | ${r.moderate} | ${r.elements} |`
  )
  .join('\n')}

## Automated rules failing (axe-core)

| Rule | Impact | WCAG SC | Elements | Page/viewport combos |
| --- | --- | --- | --- | --- |
${ruleRows || '| — | — | — | — | — |'}

## Findings beyond automated detection

These are derived from the captured DOM inventory, measured geometry, and real
keyboard traversal. An automated rule engine reports none of them.

| Finding | Impact | WCAG SC | Pages affected |
| --- | --- | --- | --- |
${structRows || '| — | — | — | — |'}

---

_Generated ${new Date().toISOString().slice(0, 10)} by \`capture/report.mjs\`._
`

await writeFile(join(STORIES, 'Scorecard.mdx'), scorecardMdx)

// --- plain-markdown mirror for reading outside Storybook ---------------------
await mkdir(join(ROOT, 'docs'), { recursive: true })
await writeFile(
  join(ROOT, 'docs/FINDINGS.md'),
  scorecardMdx.replace(/^import .*\n/m, '').replace(/<Meta[^>]*\/>\n/, '').trimStart()
)

console.log(`\nGenerated ${storyCount} story files + ${storyCount} findings pages`)
console.log(`Scorecard: ${tot.critical} critical, ${tot.serious} serious, ${tot.moderate} moderate`)
console.log(`           ${tot.elements} element occurrences\n`)
