import { renderSnapshot, getMeta } from '../../lib/snapshot.js'

// Generated by capture/report.mjs — edit capture/targets.json and re-run `pnpm report`.

export default {
  title: 'Journeys/Hotel Details/Hotel Detail',
  parameters: {
    docs: {
      description: {
        component: `Property overview, amenities, map, policies, and the Select Your Room table.

**Source:** production capture of \`presto.eventpipe.com/event/9f16e139-935b-48f6-80cf-da2628b33b9c/shopKey/6a6b79b85171a074d87851cd/hotel/48415cdb-dfea-4cb1-90e0-f678196a1702\`
Rendered from the exact DOM the browser built, with production CSS, inside a shadow root.
Open the **Accessibility** panel to run axe against the real markup.`,
      },
    },
  },
}

export const Desktop = {
  name: 'Desktop 1440px',
  render: () => renderSnapshot({ journey: 'details', id: 'hotel-detail', viewport: 'desktop' }),
}

export const Mobile = {
  name: 'Mobile 390px',
  render: () => renderSnapshot({ journey: 'details', id: 'hotel-detail', viewport: 'mobile' }),
}
