import { renderSnapshot, getMeta } from '../../lib/snapshot.js'

// Generated by capture/report.mjs — edit capture/targets.json and re-run `pnpm report`.

export default {
  title: 'Journeys/Manage Booking/Manage Booking - Reservation',
  parameters: {
    docs: {
      description: {
        component: `Authenticated reservation management: modify, cancel, resend confirmation.

**Source:** production capture of \`pending\`
Rendered from the exact DOM the browser built, with production CSS, inside a shadow root.
Open the **Accessibility** panel to run axe against the real markup.`,
      },
    },
  },
}

export const Desktop = {
  name: 'Desktop 1440px',
  render: () => renderSnapshot({ journey: 'managebooking', id: 'manage-booking-detail', viewport: 'desktop' }),
}

export const Mobile = {
  name: 'Mobile 390px',
  render: () => renderSnapshot({ journey: 'managebooking', id: 'manage-booking-detail', viewport: 'mobile' }),
}
