import { renderSnapshot, getMeta } from '../../lib/snapshot.js'

// Generated by capture/report.mjs — edit capture/targets.json and re-run `pnpm report`.

export default {
  title: 'Journeys/Confirmation/Booking Confirmation',
  parameters: {
    docs: {
      description: {
        component: `Post-booking confirmation with reservation number and summary.

**Source:** production capture of \`pending\`
Rendered from the exact DOM the browser built, with production CSS, inside a shadow root.
Open the **Accessibility** panel to run axe against the real markup.`,
      },
    },
  },
}

export const Desktop = {
  name: 'Desktop 1440px',
  render: () => renderSnapshot({ journey: 'confirmation', id: 'confirmation', viewport: 'desktop' }),
}

export const Mobile = {
  name: 'Mobile 390px',
  render: () => renderSnapshot({ journey: 'confirmation', id: 'confirmation', viewport: 'mobile' }),
}
