import { renderSnapshot, getMeta } from '../../lib/snapshot.js'

// Generated by capture/report.mjs — edit capture/targets.json and re-run `pnpm report`.

export default {
  title: 'Journeys/Checkout/3. Payment Information',
  parameters: {
    docs: {
      description: {
        component: `Step 3. Card entry and billing address. CAPTURED ONLY - never submitted.

**Source:** production capture of \`pending\`
Rendered from the exact DOM the browser built, with production CSS, inside a shadow root.
Open the **Accessibility** panel to run axe against the real markup.`,
      },
    },
  },
}

export const Desktop = {
  name: 'Desktop 1440px',
  render: () => renderSnapshot({ journey: 'checkout', id: 'checkout-3-payment', viewport: 'desktop' }),
}

export const Mobile = {
  name: 'Mobile 390px',
  render: () => renderSnapshot({ journey: 'checkout', id: 'checkout-3-payment', viewport: 'mobile' }),
}
