import { renderSnapshot, getMeta } from '../../lib/snapshot.js'

// Generated by capture/report.mjs — edit capture/targets.json and re-run `pnpm report`.

export default {
  title: 'Journeys/Landing/Event Landing',
  parameters: {
    docs: {
      description: {
        component: `Event entry point — hero, event branding, and the initial search form. First page in the journey; everything else is reached from here.

**Source:** production capture of \`presto.eventpipe.com/event/9f16e139-935b-48f6-80cf-da2628b33b9c/\`
Rendered from the exact DOM the browser built, with production CSS, inside a shadow root.
Open the **Accessibility** panel to run axe against the real markup.`,
      },
    },
  },
}

export const Desktop = {
  name: 'Desktop 1440px',
  render: () => renderSnapshot({ journey: 'landing', id: 'event-landing', viewport: 'desktop' }),
}

export const Mobile = {
  name: 'Mobile 390px',
  render: () => renderSnapshot({ journey: 'landing', id: 'event-landing', viewport: 'mobile' }),
}
